"""Add Orders Model

Revision ID: 4f61c23fda75
Revises: d17661787ad2
Create Date: 2024-04-17 23:17:10.018552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f61c23fda75"
down_revision: Union[str, None] = "d17661787ad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("customer", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "Веб-Сайт",
                "Telegram Bot",
                "Работа с серверами",
                "Верстка",
                "Скрипт",
                name="ordertype",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "Рассмотрение",
                "Согласование",
                "В работе",
                "Тестирование",
                "Завершенный",
                name="orderstatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tech_task_filename", sa.String(), nullable=True),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    sa.Enum(name='ordertype').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='orderstatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
