"""Add Reviews Model

Revision ID: d17661787ad2
Revises: 7105b5d7f068
Create Date: 2024-04-17 13:53:07.242546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d17661787ad2"
down_revision: Union[str, None] = "7105b5d7f068"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("author", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.Date(), nullable=False),
        sa.CheckConstraint("rating <= 5", name="check_rating_not_more_five"),
        sa.CheckConstraint("rating >= 0", name="check_rating_positive"),
        sa.ForeignKeyConstraint(
            ["author"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_rating_positive", "reviews")
    op.drop_constraint("check_rating_not_more_five", "reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
