"""Add PromoCode Model

Revision ID: 57019ef6eb81
Revises: 58dd89dd721d
Create Date: 2024-04-19 19:57:48.541756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57019ef6eb81"
down_revision: Union[str, None] = "58dd89dd721d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promocode",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("discount", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.CheckConstraint("discount < 100", name="check_not_more_100_discount"),
        sa.CheckConstraint("discount > 0", name="check_positive_discount"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_not_more_100_discount', 'promocode')
    op.drop_constraint('check_positive_discount', 'promocode')
    op.drop_table("promocode")
    # ### end Alembic commands ###
